from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserViewSet, PostViewSet, CategoryViewSet, 
    TagViewSet, CommentViewSet, AnalyticsViewSet
)
from .hello import hello  # Import your hello view

# Create router and register viewsets
router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'posts', PostViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'tags', TagViewSet)
router.register(r'comments', CommentViewSet)
router.register(r'analytics', AnalyticsViewSet, basename='analytics')

# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('', include(router.urls)),  # DRF viewsets
    path('hello/', hello),           # Simple hello route
]

# URL patterns generated by the router:
# GET /users/ - List all users
# POST /users/ - Create new user
# GET /users/{id}/ - Retrieve user
# PUT /users/{id}/ - Update user
# PATCH /users/{id}/ - Partial update user
# DELETE /users/{id}/ - Delete user
# GET /users/me/ - Current user profile
# PATCH /users/update_profile/ - Update current user
# GET /users/{id}/posts/ - User's posts

# GET /posts/ - List all posts
# POST /posts/ - Create new post
# GET /posts/{id}/ - Retrieve post
# PUT /posts/{id}/ - Update post
# PATCH /posts/{id}/ - Partial update post
# DELETE /posts/{id}/ - Delete post
# POST /posts/{id}/like/ - Like/unlike post
# GET /posts/featured/ - Featured posts
# GET /posts/popular/ - Popular posts
# GET /posts/trending/ - Trending posts
# GET /posts/my_posts/ - Current user's posts

# Similar patterns exist for categories, tags, comments, and analytics

# Additional simple test route:
# GET /hello/ - Returns {"message": "HELLO, API!"}
